"use client";
import { ArrowLeft, Loader2, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
export type Wijk={id:string;name:string;description:string;coordinator:string|null;contact:string|null;sortOrder:number};type FormState={name:string;description:string;coordinator:string;contact:string;sortOrder:number};const empty:FormState={name:"",description:"",coordinator:"",contact:"",sortOrder:0};const toForm=(w:Wijk):FormState=>({name:w.name,description:w.description,coordinator:w.coordinator??"",contact:w.contact??"",sortOrder:w.sortOrder});
export function WijkForm({initialItem}:{initialItem?:Wijk}){const router=useRouter();const[form,setForm]=useState<FormState>(initialItem?toForm(initialItem):empty);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");const isEdit=Boolean(initialItem);function update<K extends keyof FormState>(k:K,v:FormState[K]){setForm(c=>({...c,[k]:v}))}async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setNotice("");try{const r=await fetch(isEdit?`/api/admin/organization/wijk/${initialItem?.id}`:"/api/admin/organization/wijk",{method:isEdit?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message??"Gagal menyimpan wijk");setNotice(j.message);if(!isEdit)router.replace(`/organization/wijk/${j.data.id}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan wijk")}finally{setSaving(false)}}async function remove(){if(!initialItem||!confirm(`Hapus wijk ${initialItem.name}?`))return;setSaving(true);try{const r=await fetch(`/api/admin/organization/wijk/${initialItem.id}`,{method:"DELETE"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);router.replace("/organization");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Gagal menghapus wijk")}finally{setSaving(false)}}return <form className="py-6" onSubmit={save}><section className="rounded-md border border-slate-200 bg-white shadow-sm"><Header title={isEdit?"Read / Update Wijk":"Create Wijk"} saving={saving} remove={isEdit?remove:undefined}/><div className="grid gap-4 p-4">{notice?<Alert tone="good" text={notice}/>:null}{error?<Alert tone="bad" text={error}/>:null}<div className="grid gap-4 md:grid-cols-2"><Field label="Nama" value={form.name} onChange={v=>update("name",v)}/><Field label="Koordinator" value={form.coordinator} onChange={v=>update("coordinator",v)}/><Field label="Kontak" value={form.contact} onChange={v=>update("contact",v)}/><Field label="Sort Order" type="number" value={String(form.sortOrder)} onChange={v=>update("sortOrder",Number(v))}/></div><Text label="Description" value={form.description} onChange={v=>update("description",v)}/></div></section></form>}
function Header({title,saving,remove}:{title:string;saving:boolean;remove?:()=>void}){return <div className="flex items-center justify-between border-b border-slate-200 p-4"><div><Link href="/organization" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={16}/>Kembali ke daftar</Link><h3 className="mt-3 font-bold">{title}</h3></div><div className="flex gap-2">{remove?<button type="button" onClick={remove} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md border border-red-200 px-3 text-sm font-bold text-red-700"><Trash2 size={16}/>Hapus</button>:null}<button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-slate-950 px-3 text-sm font-bold text-white">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Simpan</button></div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input required className="h-10 rounded-md border border-slate-300 px-3 text-sm" type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<textarea required rows={6} className="rounded-md border border-slate-300 px-3 py-2 text-sm leading-6" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Alert({tone,text}:{tone:"good"|"bad";text:string}){return <div className={`rounded-md border px-3 py-2 text-sm ${tone==="good"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{text}</div>}
