"use client";

import { ArrowLeft, Loader2, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

type Status = "DRAFT" | "PUBLISHED" | "ARCHIVED";
type Category = "BERITA_KEGIATAN" | "ARTIKEL_RENUNGAN" | "PUBLIKASI_RESMI";
export type Publication = { id: string; slug: string; title: string; category: Category; excerpt: string; content: string[]; author: string; publishedAt: string | null; thumbnailUrl: string | null; thumbnailTone: string | null; readTime: string | null; seoTitle: string | null; seoDescription: string | null; status: Status };
type FormState = Omit<Publication, "id" | "content" | "publishedAt"> & { contentText: string; publishedAt: string };
const categories: { value: Category; label: string }[] = [{ value: "BERITA_KEGIATAN", label: "Berita Kegiatan" }, { value: "ARTIKEL_RENUNGAN", label: "Artikel dan Renungan" }, { value: "PUBLIKASI_RESMI", label: "Publikasi Resmi" }];
const statuses: Status[] = ["DRAFT", "PUBLISHED", "ARCHIVED"];
const emptyForm: FormState = { slug: "", title: "", category: "BERITA_KEGIATAN", excerpt: "", contentText: "", author: "Tim Publikasi", publishedAt: new Date().toISOString().slice(0, 10), thumbnailUrl: "", thumbnailTone: "", readTime: "3 menit baca", seoTitle: "", seoDescription: "", status: "DRAFT" };
const toSlug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9 -]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
const toForm = (item: Publication): FormState => ({ ...item, publishedAt: item.publishedAt ? item.publishedAt.slice(0, 10) : "", contentText: item.content.join("\n\n"), thumbnailUrl: item.thumbnailUrl ?? "", thumbnailTone: item.thumbnailTone ?? "", readTime: item.readTime ?? "", seoTitle: item.seoTitle ?? "", seoDescription: item.seoDescription ?? "" });

export function PublicationForm({ initialItem }: { initialItem?: Publication }) {
  const router = useRouter();
  const [form, setForm] = useState<FormState>(initialItem ? toForm(initialItem) : emptyForm);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const isEdit = Boolean(initialItem);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setNotice(""); setError(""); const payload = { ...form, slug: toSlug(form.slug || form.title), publishedAt: form.publishedAt ? new Date(form.publishedAt).toISOString() : null, content: form.contentText.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean) }; try { const response = await fetch(isEdit ? `/api/admin/publications/${initialItem?.id}` : "/api/admin/publications", { method: isEdit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message ?? "Gagal menyimpan publikasi"); setNotice(result.message); if (!isEdit) router.replace(`/publications/${result.data.id}`); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Gagal menyimpan publikasi"); } finally { setSaving(false); } }
  async function remove() { if (!initialItem || !confirm(`Hapus publikasi "${initialItem.title}"?`)) return; setSaving(true); try { const response = await fetch(`/api/admin/publications/${initialItem.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message); router.replace("/publications"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Gagal menghapus publikasi"); } finally { setSaving(false); } }
  return <form className="py-6" onSubmit={save}><section className="rounded-md border border-slate-200 bg-white shadow-sm"><Header title={isEdit ? "Read / Update Publikasi" : "Create Publikasi"} saving={saving} remove={isEdit ? remove : undefined}/><div className="grid gap-4 p-4">{notice ? <Alert tone="good" text={notice}/> : null}{error ? <Alert tone="bad" text={error}/> : null}<div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={form.title} onChange={(value) => update("title", value)} onBlur={() => !form.slug && update("slug", toSlug(form.title))} required/><Field label="Slug" value={form.slug} onChange={(value) => update("slug", value)} required/><Select label="Kategori" value={form.category} onChange={(value) => update("category", value as Category)} options={categories}/><Select label="Status" value={form.status} onChange={(value) => update("status", value as Status)} options={statuses.map((status) => ({ value: status, label: status }))}/><Field label="Author" value={form.author} onChange={(value) => update("author", value)} required/><Field label="Tanggal Publish" type="date" value={form.publishedAt} onChange={(value) => update("publishedAt", value)}/><Field label="Read Time" value={form.readTime ?? ""} onChange={(value) => update("readTime", value)}/><Field label="Thumbnail URL" value={form.thumbnailUrl ?? ""} onChange={(value) => update("thumbnailUrl", value)}/></div><Text label="Excerpt" value={form.excerpt} onChange={(value) => update("excerpt", value)} required/><Text label="Content" value={form.contentText} onChange={(value) => update("contentText", value)} rows={12}/><div className="grid gap-4 md:grid-cols-2"><Field label="SEO Title" value={form.seoTitle ?? ""} onChange={(value) => update("seoTitle", value)}/><Field label="SEO Description" value={form.seoDescription ?? ""} onChange={(value) => update("seoDescription", value)}/></div></div></section></form>;
}
function Header({ title, saving, remove }: { title: string; saving: boolean; remove?: () => void }) { return <div className="flex items-center justify-between border-b border-slate-200 p-4"><div><Link className="inline-flex items-center gap-2 text-sm font-bold text-slate-600" href="/publications"><ArrowLeft size={16}/>Kembali ke daftar</Link><h3 className="mt-3 font-bold">{title}</h3></div><div className="flex gap-2">{remove ? <button type="button" onClick={remove} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md border border-red-200 px-3 text-sm font-bold text-red-700"><Trash2 size={16}/>Hapus</button> : null}<button disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-slate-950 px-3 text-sm font-bold text-white">{saving ? <Loader2 className="animate-spin" size={16}/> : <Save size={16}/>}Simpan</button></div></div>; }
function Field({ label, value, onChange, type = "text", required, onBlur }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; onBlur?: () => void }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input className="h-10 rounded-md border border-slate-300 px-3 text-sm" type={type} value={value} required={required} onBlur={onBlur} onChange={(event) => onChange(event.target.value)}/></label>; }
function Text({ label, value, onChange, rows = 4, required }: { label: string; value: string; onChange: (value: string) => void; rows?: number; required?: boolean }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<textarea className="rounded-md border border-slate-300 px-3 py-2 text-sm leading-6" rows={rows} value={value} required={required} onChange={(event) => onChange(event.target.value)}/></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<select className="h-10 rounded-md border border-slate-300 bg-white px-3 text-sm" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function Alert({ tone, text }: { tone: "good" | "bad"; text: string }) { return <div className={`rounded-md border px-3 py-2 text-sm ${tone === "good" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{text}</div>; }
